apiVersion: v1
appVersion: V1.0
description: 'Het Landelijke Tabellen Component voorziet in het ontsluiten van de landelijke index tabellen van BZK (NL dus) waar je bijvoorbeeld gemeenten nummers kan terugvinden. Het voorziet in die zin in het via API beschikbaar stellen van niet Common Ground bronnen.'
name: landelijketabellencatalogus
version: 0.1.0
home: https://www.conduction.nl
icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
      condition: redis.enabled