apiVersion: v1
entries:
  ltc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-25T15:09:52.6972123Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 3fee1136621eb3d9c4e8234905d005d79dd5a5ffab8f77fc75778865136734dc
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: ltc
    urls:
    - ltc-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-25T15:09:52.6758992Z"
